package com.bitshammer.business.domain;

public enum Category {
	
    ARTS_PHOTOGRAPHY,
    AUDIOBOOKS,
    BIOGRAPHIES_MEMOIRS,
    BUSINESS_INVESTING,
    CHILDRENS_BOOKS,
    COMICS,
    COOKBOOKS,
    CRAFTS,
    FASHION,
    HISTORY,
    HUMOR_ENTERTAINMENT,
    LITERATURE_FICTION,
    MYSTERY_THRILLER_SUSPENSE,
    NONFICTION,
    RELIGION,
    ROMANCE,
    SCIENCE,
    SCIENCE_FICTION_FANTASY,
    SPORTS_OUTDOORS,
    TEEN_YOUNG
	

}
